### ISSUE TITLE
[Feat] 돌출입 검사 기능 및 날짜별 조회/삭제

### ISSUE THREAD

**Issue by rlawns0327** [DEU-Smiley/Smiley-BackEnd#118]
## 📝 Description
돌출입 검사 기능 구현

## 📍 Todo
- [x] 기존 파이썬 코드에서 학습된 파일을 아이디/날짜.jpg 형식으로 저장하도록 파이썬 코드 변경
- [x] 파이썬 코드 동작 확인
- [x] controller 구현
- [x] service 구현
- [x] 윈도우 환경 동작 테스트
- [x] 리눅스 환경 적용을 위한 코드 구현
