### ISSUE TITLE
[Feat] 커뮤니티 게시판 기능

### ISSUE THREAD

**Issue by effort-type** [DEU-Smiley/Smiley-BackEnd#120]
## 📝 Description
커뮤니티 게시판 CRUD 기능 구현

## 📍 Todo
- [x] 커뮤니티 관련 Entity 생성
- [x] Dto 생성
- [x] Controller 생성 및 구현
- [x] Service 생성 및 구현
- [x] 패키지 분리해서 가독성 높이기
- [x] enum 타입 카테고리 url 소문자로 변경하기
