### ISSUE TITLE
User DB 변경

### ISSUE THREAD

**Issue by effort-type** [DEU-Smiley/Smiley-BackEnd#133]
## 📝 Description
기존 User Entity를 커뮤니티 게시물을 저장할 수 있도록 변경

## 📍 Todo
- [x] 기존 User Entity에 게시물을 저장할 수 있도록 컬럼 추가
- [x] User Entity primary key 변경으로 인한 로직 변경
- [x] 테스트 코드 작성
- [x] 기존 기능 동작 테스트 후 전달

**Comment by effort-type** [comment]
User Entity primary key가 id -> userNumber로 변경됨으로 인해 isBlank 메소드를 사용하여 체크하도록 변경
