### ISSUE TITLE
[Feat/Fix] 병원 예약 기능 수정

### ISSUE THREAD

**Issue by rlawns0327** [DEU-Smiley/Smiley-BackEnd#148]
## 📝 Description
1. 현재 예약 정보 조회 시,  리스트가 아닌 dto 하나만 return하게 되어 있어 2개 이상 데이터가 있으면 오류남
2. 예약 시, memo에 값이 들어가지 않아 memo 부분 항상 null
3. 예약 시, 의사 이름 추가
4. 예약 번호 해시값 처리하여 추가
5. 예약 관련 api URL 수정
## 📍 Todo
- [x] 응답형식을 UserBookingDto가 아닌 리스트로 뱉도록 변환
- [x] memo 값 들어가도록 수정 
- [x] 예약 시, 의사 이름 추가 ( 임시로 랜덤 이름 )
- [x] 예약 번호 해시값 처리하여 추가
- [x] api URL 수정
