### ISSUE TITLE
[FEAT] 사용자 의료정보 저장

### ISSUE THREAD

**Issue by tjdckscert** [DEU-Smiley/Smiley-BackEnd#20]
## 📝 Description
앱에서 사용자의  의료정보를 넘겨주면 UserMedicalInfo 테이블에 저장한다.

## 📍 Todo
- [x] UserMedicalInfo Repository 생성
- [x] DTO 작성
- [x] UserMedicalInfoService 생성
- [x] UserController에 의료정보 저장 기능 추가
- [x] Hospital id long으로 변경
