### ISSUE TITLE
[Feat] 입력받은 갯수만큼의 매거진 가져오기

### ISSUE THREAD

**Issue by tjdckscert** [DEU-Smiley/Smiley-BackEnd#40]
## 📝 Description
입력받은 갯수만큼의 매거진을 가져와서 반환해준다.

## 📍 Todo
- [x] MagazineController 기능 추가
- [x] MagazineRespository 기능 추가
- [x] MagazineService 기능 추가

**Comment by tjdckscert** [comment]
![image](https://user-images.githubusercontent.com/115801420/230335672-6354e970-4d62-4c25-87b1-f50a4bdc4ede.png)

- Result
