### ISSUE TITLE
[Feat] 상태측정1 - 칫솔모 상태 측정 기능

### ISSUE THREAD

**Issue by rlawns0327** [DEU-Smiley/Smiley-BackEnd#58]
## 📝 Description
칫솔모 이미지를 받으면  파이썬을 통한 상태 측정 후 해당 결과 이미지를 반환하는 기능

## 📍 Todo
- [x] 이미지와 함께 요청이 들어오면 , multipartfile을 이용하여 파일 업로드가 가능하도록 Controller 구현하기
- [x] ToothBrushStatusService 생성하기
- [x] 저장할 이미지 / 학습된 이미지 / 학습용 모델 / 학습 파일의 절대 경로 관리를 위한 application-path.properties 추가하기
- [x] 아이디로 요청이 들어오면 아이디 값으로 이미지를 저장하도록 구현하기
- [x] 아이디로 학습된 파일을 찾아오기 때문에 기존 아이디로 학습된 이미지가 있다면 삭제하기
- [x] 학습을 위한 파이썬 코드/학습모델 추가
- [x] 학습된 이미지 파일 불러와 반환하도록 구현
