### ISSUE TITLE
github Actions를 사용하여 배포 환경 구성

### ISSUE THREAD

**Issue by rlawns0327** [DEU-Smiley/Smiley-BackEnd#7]
## 📝 Description
github Actions를 사용하여 배포 환경 구성.

## 📍 Todo
- [x] github Actions을 이용한 CI 설정 파일 작성
- [x] 서버 컴퓨터를 github actions Runner로 설정
- [x] NginX 서버 환경 구성 
- [x] 무중단 배포를 위한 스위칭용 Bash 파일 작성
