### ISSUE TITLE
[Feat] 로그인 기능 수정

### ISSUE THREAD

**Issue by tjdckscert** [DEU-Smiley/Smiley-BackEnd#80]
## 📝 Description
- 로그인 요청 시 기존 회원과 신규 회원을 구분하여 데이터를 반환 한다.

## 📍 Todo
- [x] login 기능의 이름의 signup으로 변경한다.
- [x] 반환 데이터를 구분한다.
- [x] 반환 데이터에 사용자의 의료정보를 추가한다,
